package com.softspark.chaos.flow.dto;

/** How a field's value is auto-generated by the client when a transaction type is selected. */
public enum AutogenRule {
  /** No auto-generation. */
  NONE,
  /** Seed a fresh UUID v4 (regenerate-able). */
  UUID_V4
}
