package com.softspark.chaos.flow.dto;

import com.softspark.chaos.flow.chaos.ChaosOptions;
import com.softspark.chaos.flow.chaos.NTimesOptions;
import io.soabase.recordbuilder.core.RecordBuilder;
import java.math.BigDecimal;
import org.springframework.lang.Nullable;

/**
 * REST request body for {@code POST /api/v0/flows/disbursement-batch/run} (automatic batch
 * disbursement). Carries the reservation intent, the item count N, the split mode, the outcome
 * policy, an optional per-item template, optional pacing, and optional per-event chaos.
 *
 * <p>The runner mints the {@code batch_id}/{@code batch_correlation_id} server-side (so they are
 * unique), publishes one reservation, resolves the {@code reservation_id}, splits the totals across N
 * (last item absorbs the remainder), decides each item's outcome by {@code outcomePolicy}, and
 * publishes per item {@code item.request} then {@code item.completed|item.failed}.
 *
 * @param sourceVaId the source ORGANIZATION virtual account (required)
 * @param destinationVaId the platform-float SYSTEM virtual account (required)
 * @param merchantId the merchant/organization id (required; inferred from the source VA on the UI)
 * @param currency the ISO-4217 currency code (default {@code GHS})
 * @param totalPrincipalAmount the total principal across all items (default {@code 1000.0000})
 * @param totalFees the total fees across all items (default {@code 10})
 * @param itemCount the number of items N (required; validated into {@code [1, maxBatchItems]})
 * @param disbursementSubtype {@code DOMESTIC} or {@code CROSS_BORDER} (default {@code DOMESTIC})
 * @param merchantBatchRef the merchant batch reference (autogenerated when blank)
 * @param callbackUrl an optional callback URL
 * @param authorisedUserId the authorising user id (default {@code chaos-operator})
 * @param authorisedKeyFingerprint the authorising key fingerprint (default {@code ab:cd:ef:00})
 * @param tenantId an optional tenant override
 * @param correlationId an optional correlation id (autogenerated when blank; shared by every event)
 * @param splitMode the split mode (default {@code EVEN}; only {@code EVEN} is currently supported)
 * @param outcomePolicy the per-item outcome policy (required)
 * @param creditProviderId the per-item credit provider id (default {@code PROVIDER_GH})
 * @param creditAccountId the per-item credit account id (default {@code 0240000000})
 * @param providerId the per-item payment provider id (default {@code PROVIDER_GH})
 * @param sourceCountry the per-item source country (cross-border; nullable)
 * @param destinationCountry the per-item destination country (cross-border; nullable)
 * @param feeVaId the SYSTEM fee-revenue virtual account credited with each item's fee (nullable)
 * @param failureCode the failure code applied to failed items (default {@code RECIPIENT_INVALID})
 * @param failureReason the failure reason applied to failed items
 * @param pacing optional pacing for the item loop (count is ignored; N drives the item count)
 * @param chaos optional chaos applied to each item event
 */
@RecordBuilder
public record BatchDisbursementRunRequest(
    @Nullable String sourceVaId,
    @Nullable String destinationVaId,
    @Nullable String merchantId,
    @Nullable String currency,
    @Nullable BigDecimal totalPrincipalAmount,
    @Nullable BigDecimal totalFees,
    int itemCount,
    @Nullable String disbursementSubtype,
    @Nullable String merchantBatchRef,
    @Nullable String callbackUrl,
    @Nullable String authorisedUserId,
    @Nullable String authorisedKeyFingerprint,
    @Nullable String tenantId,
    @Nullable String correlationId,
    @Nullable String splitMode,
    @Nullable BatchOutcomePolicy outcomePolicy,
    @Nullable String creditProviderId,
    @Nullable String creditAccountId,
    @Nullable String providerId,
    @Nullable String sourceCountry,
    @Nullable String destinationCountry,
    @Nullable String feeVaId,
    @Nullable String failureCode,
    @Nullable String failureReason,
    @Nullable NTimesOptions pacing,
    @Nullable ChaosOptions chaos) {}
