package com.softspark.chaos.flow.dto;

import io.soabase.recordbuilder.core.RecordBuilder;
import java.math.BigDecimal;
import org.springframework.lang.Nullable;

/**
 * A single operator-supplied fee row on a {@link PublishFlowRequest}, assembled by the dynamic fee
 * form ({@link FieldKind#FEE_LIST}). Builders map each {@code FeeInput} to a wire
 * {@link com.softspark.chaos.flow.model.v1.TransactionFeeLine}, autogenerating {@code feeCode} when
 * blank and applying a per-flow default {@code feeType} when blank.
 *
 * @param feeType the ledger {@code TransactionFeeType} name (e.g. {@code PLATFORM}); per-flow default
 *     applied when blank
 * @param amount the fee amount
 * @param feeCode the fee reference code; autogenerated (ULID) by the builder when blank
 * @param destinationVaId the system fee-revenue virtual account credited with this fee
 */
@RecordBuilder
public record FeeInput(
    @Nullable String feeType,
    @Nullable BigDecimal amount,
    @Nullable String feeCode,
    @Nullable String destinationVaId) {}
