package com.softspark.chaos.flow.dto;

/**
 * The UI/semantic kind of a flow field, used by the Single Flow Run form to choose a control and
 * seeding behaviour.
 */
public enum FieldKind {
  /** Free text input. */
  TEXT,
  /** A UUID value; usually paired with {@link AutogenRule#UUID_V4}. */
  UUID,
  /** A decimal monetary amount. */
  AMOUNT,
  /** An ISO-8601 timestamp. */
  DATETIME,
  /** A constrained choice rendered from {@code options}. */
  SELECT,
  /** A virtual-account reference, picked from VAs filtered by {@code accountKind}. */
  VA_REF,
  /**
   * A repeatable list of fee rows. Each row carries an {@code AMOUNT}, a SYSTEM fee-revenue VA
   * picker (the row's {@code destination_va_id}), an autogenerated {@code fee_code}, and a fixed
   * {@code fee_type}. The renderer assembles the rows into the request's typed top-level
   * {@code fees[]} (not {@code flowFields}).
   */
  FEE_LIST,
  /**
   * A country selection whose options come from the supported-countries table (Phase 010). The
   * backend marks the kind and seeds a {@code defaultValue} (ISO code, e.g. {@code GH}); the client
   * fetches the option list.
   */
  COUNTRY
}
