import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { type FeeInput, type VirtualAccountResponse } from "@/lib/api";
import { ulid } from "@/lib/ulid";
import { Plus, RefreshCw, X } from "lucide-react";

// Ledger TransactionFeeType names (no _FEE suffix).
const FEE_TYPES = ["PLATFORM", "PROVIDER", "FX_MARGIN", "SURCHARGE"];

/** A fresh fee row: blank amount/VA, autogen fee_code, default PLATFORM fee_type. */
export function emptyFeeRow(): FeeInput {
  return { amount: "", destinationVaId: "", feeCode: ulid(), feeType: "PLATFORM" };
}

function vaLabel(va: VirtualAccountResponse): string {
  const id = va.vaId.length > 12 ? `${va.vaId.slice(0, 8)}…` : va.vaId;
  return `${va.name} · ${id} · ${va.currency}`;
}

function sumFees(rows: FeeInput[]): number {
  return rows.reduce((acc, r) => acc + (parseFloat(String(r.amount ?? "")) || 0), 0);
}

/**
 * The dynamic fee list ({@code FieldKind.FEE_LIST}). Each row is an amount + a SYSTEM fee-revenue VA
 * picker, with an autogenerated {@code fee_code} and an editable {@code fee_type} (default
 * {@code PLATFORM}). Rows add/remove; a read-only Gross = net + Σ fees is shown live. The rows are
 * reported to the parent as the typed top-level {@code fees[]} of the PublishFlowRequest.
 */
export function FeeListField({
  rows,
  onChange,
  systemVas,
  loading,
  net
}: {
  rows: FeeInput[];
  onChange: (rows: FeeInput[]) => void;
  systemVas: VirtualAccountResponse[];
  loading: boolean;
  net: string;
}) {
  const update = (index: number, patch: Partial<FeeInput>) =>
    onChange(rows.map((r, i) => (i === index ? { ...r, ...patch } : r)));
  const add = () => onChange([...rows, emptyFeeRow()]);
  const remove = (index: number) => onChange(rows.filter((_, i) => i !== index));

  const total = sumFees(rows);
  const showGross = net.trim() !== "" && !Number.isNaN(parseFloat(net));
  const gross = (parseFloat(net) || 0) + total;
  const vaOptions = systemVas.map(va => ({ value: va.vaId, label: vaLabel(va) }));

  return (
    <div className="space-y-2">
      {rows.map((row, i) => (
        <div key={i} className="space-y-1.5 rounded-md border border-border p-2">
          <div className="flex items-center gap-1.5">
            <Input
              type="number"
              step="0.0001"
              placeholder="Amount"
              value={String(row.amount ?? "")}
              onChange={e => update(i, { amount: e.target.value })}
              className="text-xs"
            />
            <Select
              value={row.destinationVaId ?? ""}
              onChange={v => update(i, { destinationVaId: v })}
              options={vaOptions}
              placeholder={loading ? "Loading…" : "Fee VA (SYSTEM)…"}
              searchable
              searchPlaceholder="Search accounts…"
              emptyText="No matching virtual accounts."
            />
            <Button
              type="button"
              variant="outline"
              size="icon"
              title="Remove fee"
              disabled={rows.length <= 1}
              onClick={() => remove(i)}
            >
              <X className="h-3.5 w-3.5" />
            </Button>
          </div>
          <div className="flex items-center gap-1.5">
            <Select
              value={row.feeType ?? "PLATFORM"}
              onChange={v => update(i, { feeType: v })}
              options={FEE_TYPES.map(t => ({ value: t, label: t }))}
            />
            <Input
              value={row.feeCode ?? ""}
              onChange={e => update(i, { feeCode: e.target.value })}
              placeholder="fee_code"
              className="font-mono text-[11px]"
            />
            <Button
              type="button"
              variant="outline"
              size="icon"
              title="Regenerate fee code"
              onClick={() => update(i, { feeCode: ulid() })}
            >
              <RefreshCw className="h-3.5 w-3.5" />
            </Button>
          </div>
        </div>
      ))}
      <div className="flex items-center justify-between">
        <Button type="button" variant="outline" size="sm" onClick={add}>
          <Plus className="mr-1 h-3.5 w-3.5" /> Add fee
        </Button>
        <span className="text-xs text-muted-foreground">
          {showGross ? "Gross = net + Σ fees = " : "Σ fees = "}
          <strong className="font-mono text-foreground">
            {(showGross ? gross : total).toFixed(4)}
          </strong>
        </span>
      </div>
    </div>
  );
}
