spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

chaos:
  datasource:
    path: ${CHAOS_DATASOURCE_PATH:/app/data/chaos.db}
  kafka:
    cluster-label: ${CHAOS_TARGET_LABEL:staging}
